// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ProfileCards.ProfilesManagement
{

    // Info
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    internal partial class Info
    {
        public int Id { get; set; } // Id (Primary key)
        public string Value { get; set; } // Value (length: 50)
        public int PersonId { get; set; } // PersonId

        // Foreign keys

        /// <summary>
        /// Parent Person pointed by [Info].([PersonId]) (FK_Info_Person)
        /// </summary>
        public Person Person { get; set; } // FK_Info_Person

        public Info()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
