// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ProfileCards.ProfilesManagement
{

    // Person
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    internal partial class Person
    {
        public int Id { get; set; } // Id (Primary key)
        public string FirstName { get; set; } // FirstName (length: 50)
        public string ProfileImage { get; set; } // ProfileImage
        public string BackgroundImage { get; set; } // BackgroundImage
        public int SiteId { get; set; } // SiteId

        // Reverse navigation

        /// <summary>
        /// Child Infoes where [Info].[PersonId] point to this entity (FK_Info_Person)
        /// </summary>
        public System.Collections.Generic.ICollection<Info> Infoes { get; set; } // Info.FK_Info_Person
        /// <summary>
        /// Child SocialNetworks where [SocialNetwork].[PersonId] point to this entity (FK_SocialNetwork_Person)
        /// </summary>
        public System.Collections.Generic.ICollection<SocialNetwork> SocialNetworks { get; set; } // SocialNetwork.FK_SocialNetwork_Person

        // Foreign keys

        /// <summary>
        /// Parent Site pointed by [Person].([SiteId]) (FK_Person_Site)
        /// </summary>
        public Site Site { get; set; } // FK_Person_Site

        public Person()
        {
            Infoes = new System.Collections.Generic.List<Info>();
            SocialNetworks = new System.Collections.Generic.List<SocialNetwork>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
