// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ProfileCards.ProfilesManagement
{

    // Site
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    internal partial class Site
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 50)
        public string Url { get; set; } // Url (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child People where [Person].[SiteId] point to this entity (FK_Person_Site)
        /// </summary>
        public System.Collections.Generic.ICollection<Person> People { get; set; } // Person.FK_Person_Site

        public Site()
        {
            People = new System.Collections.Generic.List<Person>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
