// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ProfileCards.ProfilesManagement
{

    // SocialNetwork
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    internal partial class SocialNetworkConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SocialNetwork>
    {
        public SocialNetworkConfiguration()
            : this("dbo")
        {
        }

        public SocialNetworkConfiguration(string schema)
        {
            ToTable("SocialNetwork", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.Url).HasColumnName(@"Url").HasColumnType("nvarchar(max)").IsRequired();
            Property(x => x.PersonId).HasColumnName(@"PersonId").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.Person).WithMany(b => b.SocialNetworks).HasForeignKey(c => c.PersonId).WillCascadeOnDelete(false); // FK_SocialNetwork_Person
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
